AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Umbrella template for all stacks in the application
Resources:
  DataResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./data-resources/template.yaml
  SageMakerResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sagemaker-resources/template.yaml
    DependsOn:
      - DataResources
  TranscriptOrchestration:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./transcript-orchestration/template.yaml
      Parameters:
        BucketName: !GetAtt DataResources.Outputs.BucketName
        ModelName: !GetAtt SageMakerResources.Outputs.ModelName